name: Release Linux App

on:
  push:
    tags:
      - 'v*'
  # workflow_dispatch:
  #   inputs:
  #     tag:
  #       description: 'Version tag'
  #       required: true
  #       default: 'v0.0.1'

jobs:
  release:
    name: Release Linux App
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        platform:
          - amd64

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: stable

      - name: Setup wails
        shell: bash
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Install Ubuntu prerequisites
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Build frontend
        shell: bash
        run: |
          cd frontend
          pnpm install
          pnpm build

      - name: Build Linux app
        shell: bash
        if: github.event.release.tag_name
        run: |
          wails build -platform linux/${{ matrix.platform }} \
          -s \
          -skipbindings	\
          -o bb-music-linux-${{ matrix.platform }}-${{github.event.release.tag_name}}

      - name: Setup UPX
        uses: crazy-max/ghaction-upx@v3
        with:
          install-only: true

      - name: Compress
        run: |
          upx ./build/bin/bb-music-linux-${{ matrix.platform }}-${{github.event.release.tag_name}}

      - name: Upload release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ./build/bin/*
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ github.event.release.tag_name }}
          tag_name: ${{ github.event.release.tag_name }}
